# Generated by Django 5.2.5 on 2025-09-07 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato'), ('otro', 'Otro')], max_length=10)),
                ('raza', models.CharField(blank=True, max_length=100)),
                ('edad', models.PositiveIntegerField(help_text='Edad en meses')),
                ('sexo', models.CharField(choices=[('macho', 'Macho'), ('hembra', 'Hembra')], max_length=10)),
                ('descripcion', models.TextField(help_text='Descripción de la mascota')),
                ('ubicacion', models.CharField(help_text='Ciudad o ubicación donde se encuentra la mascota', max_length=200)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='mascotas/')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('adoptado', 'Adoptado'), ('reservado', 'Reservado')], default='disponible', max_length=15)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
