# Generated by Django 5.2.5 on 2025-09-07 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FiltroBusqueda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_filtro', models.CharField(help_text='Nombre para identificar este filtro', max_length=100)),
                ('tipo', models.CharField(blank=True, choices=[('perro', 'Perro'), ('gato', 'Gato'), ('otro', 'Otro')], max_length=10, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('macho', 'Macho'), ('hembra', 'Hembra')], max_length=10, null=True)),
                ('edad_min', models.PositiveIntegerField(blank=True, help_text='Edad mínima en meses', null=True)),
                ('edad_max', models.PositiveIntegerField(blank=True, help_text='Edad máxima en meses', null=True)),
                ('ubicacion', models.CharField(blank=True, help_text='Ciudad o ubicación', max_length=200)),
                ('raza', models.CharField(blank=True, help_text='Raza específica', max_length=100)),
                ('incluir_descripcion', models.BooleanField(default=False, help_text='Incluir búsqueda en descripción')),
                ('texto_busqueda', models.CharField(blank=True, help_text='Texto a buscar en nombre o descripción', max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultimo_uso', models.DateTimeField(auto_now=True)),
                ('es_favorito', models.BooleanField(default=False, help_text='Marcar como filtro favorito')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filtros_busqueda', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Filtro de Búsqueda',
                'verbose_name_plural': 'Filtros de Búsqueda',
                'ordering': ['-fecha_ultimo_uso'],
            },
        ),
        migrations.CreateModel(
            name='HistorialBusqueda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterios_busqueda', models.JSONField(help_text='Criterios de búsqueda aplicados')),
                ('resultados_encontrados', models.PositiveIntegerField(default=0)),
                ('fecha_busqueda', models.DateTimeField(auto_now_add=True)),
                ('filtro_aplicado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filtros.filtrobusqueda')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_busquedas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Búsqueda',
                'verbose_name_plural': 'Historial de Búsquedas',
                'ordering': ['-fecha_busqueda'],
            },
        ),
    ]
